// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sexrpfwmzmnsukyoksmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNleHJwZndtem1uc3VreW9rc21nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NzY4MTgsImV4cCI6MjA3NDI1MjgxOH0.lfFoLhZ_rh9OLMBuwVp3Yj5jk3IwW0Hv9f4xliNEM48";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});